apiVersion: v1
kind: Pod
metadata:
  name: stress
spec:
  containers:
    - image: sahiya/stress
      imagePullPolicy: Always
      name: stress
      command: ["sleep", "200"]
      resources:
       requests:
        cpu: "100m" ## 1cpu=1000mi cpu
        memory: "200Mi"
       limits:
        cpu: "200Mi"
        memory: "300Mi" 
  
      