apiVersion: v1
kind: Pod
metadata: 
 name: env
spec:
 containers:
 - image: nginx
   name: nginx
   env:
   - name: course
     value: docker amd k8
   - name: learner
     value: sahiya
   - name: duration
     value: 25hr       