# ---
# apiVersion: v1
# kind: Pod
# metadata: 
#  name: config-pod
# spec:
#  containers:
#  - image: nginx
#    name: nginx
#    env:
#    - name: course
#      valueFrom:
#       configMapKeyRef:
#        name: course-config
#        key: course
#    - name: duration
#      valueFrom:
#       configMapKeyRef:
#        name: course-config
#        key: duration           
---
apiVersion: v1
kind: Pod
metadata: 
 name: config-pod
spec:
 containers:
 - image: nginx
   name: nginx
   envFrom:
    - configMapRef:
            name: course-config
   