apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster123
  region: ap-south-1

managedNodeGroups:

# `instanceTypes` defaults to [`m5.large`]
- name: cluster-1
  spot: 
  ssh:
    publicKeyName: kuber