---
apiVersion: v1
kind: pod
metadata:
  name: nginx
  labels: 
   name: nginx
spec:
  containers:
    - image: nginx
      name: nginx
      ports:
      - containerPort: 80
---
apiVersion: v1
kind: pod
metadata:
 name: nginx-service
spec:
 selector: 
  name: nginx
ports:
  - protocol: TCp
    port: 80
    targetport: 80  
